services:
  basic-app.dev:
    image: basic-app:dev
    container_name: basic-app.dev
    build:
      context: ./app
      target: development
    ports:
      - 5173:5173
    env_file:
      - .env.dev
    volumes:
      - ./app:/app:cached
      - /app/node_modules
    working_dir: /app
    command: sh -c "pnpm db:migrate && pnpm dev --host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    depends_on:
      basic-app.db.dev:
        condition: service_healthy
    networks:
      - basic-app.network
      - basic-app.internal
    

  basic-app.db.dev:
    image: postgres:17
    container_name: basic-app.db.dev
    ports:
      - 5432:5432
    env_file:
      - .env.dev
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.dev.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - basic-app.network
      - basic-app.internal

networks:
  basic-app.network:
    name: basic-app.network
    driver: bridge
  basic-app.internal:
    name: basic-app.internal
    driver: bridge
    internal: true

volumes:
  db_data:
    driver: local
    name: basic-app.db.dev
  node_modules:
