services:
  app:
    image: app:dev
    container_name: app.dev
    build:
      context: ./app
      target: development
    ports:
      - 5173:5173
    env_file:
      - .env.dev
    volumes:
      - ./app:/app:cached
      - /app/node_modules
    working_dir: /app
    command: sh -c "pnpm db:migrate && pnpm dev --host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - app-network
      - app-internal
    

  db:
    image: postgres:17
    container_name: db.dev
    ports:
      - 5432:5432
    env_file:
      - .env.dev
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.dev.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network
      - app-internal

networks:
  app-network:
    name: app-network
    driver: bridge
  app-internal:
    external: false

volumes:
  db_data:
    driver: local
    name: db
  node_modules:
